### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [EbokianLady/pintrigue#2]
Hey Stephanie,

Great job on these! A few questions/comments.

users table: 
- [x] as we've discussed, you can take off age.
- [x] what is location used for in pinterest?

boards table:
- [x] So the categories and description come up only after you want to edit the board. For now, categories will be a bonus feature. if you still have time, you should definitely do that. I imagine that every board can have multiple categories. and the point is if you search by a word, that board will show up? So, categories can be a separate mvp with separate tables etc.

pins table looks good!

- [x] for the user/board follows, you can use a polymorphic association. so instead of having two tables, you'll only have one. check out what a polymorphic association is.

Everything else looks good! Great job!

**Comment by EbokianLady** [comment]
I've added categories to the bonus section of my MVPs and location is optional and just displays on the User profile if they add it. I'm fine leaving it to have it mirror the original, but it's not a necessary piece.

- [ ] Can you check my polymorphic association and make sure I've done it correctly? I read up on it and I believe I understand it, but I want to make sure before I close this issue.
